const WEEKLY_DATABASE_COLUMNS = [
    "QTR",
    "Week",
    "Group",
    "Number of Px on Recall List in Next 12 Months Rolling",
    "Number of Clients Added to Reactivation",
    "Recall Sucess % Monthly",
    "Number of New Eye Exams Completed",
    "Total Number of Eye Exams Completed",
    "Number of New Eye Exams Dispensed",
    "Number of New EE Booked",
    "Total Number of Eye Exams Booked",
    "# New EE - Referral",
    "# New EE - Google Ads",
    "# New EE - Local to Area",
    "# New EE - CUES CONVERSIONS",
    "# New EE - Family & Friends",
    "£ ADV - New EE Dispensed",
    "Total Number of CUES Completed",
    "Total Number of CUES put through the till",
    "Number of New CUES Completed",
    "Number of New CUES Converted to EE",
    "Number of New CUES with No Recall Assigned",
    "New EE Booked",
    "New EE Completed",
    "New EE Converted",
    "New EE ADV £",
    "New clients - Why Us",
    "Referral",
    "CUES/PEARS To EE",
    "Work Voucher",
    "Prospect",
    "Reviews on Internet",
    "Local to Area",
    "Family & Friends",
    "Number with no Why Us",
    "Branch Count",
    "Increase/Decrease",
    "Silver Plan Count",
    "Increase/Decrease",
    "Gold Plan Count",
    "Increase/Decrease",
    ]

const ID_DATABASE_COLUMNS = [
"QTR",
"Week",
"PxPublicID",
"PxTitle",
"Type",
"TransDate",
"PxLastName",
"TransPublicID",
"PaymentCategory",
"ItemDesc",
"SalesValue",
"Discount",
"NetSales",
"Sales",
"Takings",
"Refunds",
"Branch",
"StaffTitle",
"Textbox24",
"BookingDate",
"AppStartDate",
"AppType",
"AppStatusDesc",
"WhyUs",
"Name"
]


const CARE_PLANS = ['Gold', 'Silver']
const BRANCHES = ['Middleton', 'Heald Green', 'Heckmondwike', 'Cheadle']



